include formal/pin.mk

# A recipe that dies partway through must not leave a truncated target behind
# looking newer than its prerequisites — several targets here are shell
# redirections, which create the output file before the generator has written
# a byte of it.
.DELETE_ON_ERROR:

rvfi_macros.vh: $(RISCV_FORMAL_DIR)/checks/rvfi_macros.py
	python3 $^ > $@

testbench.vvp: rtl/structs.v rtl/accessor.v rtl/decoder.v rtl/executor.v rtl/fetcher.v rtl/regfile.v rtl/writeback.v rtl/littlecpu.v rvfi_macros.vh test/testbench.v test/monitor.v
	iverilog -I./rtl/ -DICARUS -DRISCV_FORMAL -DRISCV_FORMAL_COMPRESSED -DRISCV_FORMAL_ALIGNED_MEM -DRISCV_FORMAL_NRET=1 -DRISCV_FORMAL_XLEN=32 -DRISCV_FORMAL_ILEN=32 -g2012 -o $@ $^

waves.vcd: sim
	./sim

sim: test/cxxrtl.cc test/rtl.cc
	clang++ -g -std=c++14 -I $$(yosys-config --datdir)/include/backends/cxxrtl/runtime $< -o $@

test/rtl.cc: rtl/structs.v rtl/accessor.v rtl/decoder.v rtl/executor.v rtl/fetcher.v rtl/regfile.v rtl/writeback.v rtl/littlecpu.v rvfi_macros.vh test/testbench.v
	yosys -p 'read_verilog -sv $^; hierarchy -top testbench; write_cxxrtl $@'

# test/monitor.v is generated by riscv-formal's monitor/generate.py at
# RISCV_FORMAL_SHA (formal/pin.mk — bump the pin there, not here). generate.py
# opens ../insns/isa_<isa>.txt relative to its own CWD, so it must be run from
# riscv-formal/monitor/, not the repo root (see ADR-0007). The tracked file is
# regenerated in place; use `make monitor-check` to check freshness without
# touching it.
MONITOR_GEN = cd $(RISCV_FORMAL_DIR)/monitor && python3 generate.py -i rv32imc -c 1 -a -p monitor

# Depends on the generator and the pin, NOT on the clone directory: a directory's
# mtime bumps on any write anywhere inside it, which would make routine builds
# overwrite this tracked file (CLAUDE.md invariant 7) at unpredictable moments and
# defeat the point of monitor-check. The clone is order-only.
test/monitor.v: $(RISCV_FORMAL_DIR)/monitor/generate.py formal/pin.mk | $(RISCV_FORMAL_DIR)
	$(MONITOR_GEN) > $(CURDIR)/$@

.PHONY: monitor-check
monitor-check: $(RISCV_FORMAL_DIR)/monitor/generate.py | $(RISCV_FORMAL_DIR)
	@tmp=$$(mktemp "$${TMPDIR:-/tmp}/monitor-check.XXXXXX"); \
	trap 'rm -f "$$tmp"' EXIT; \
	($(MONITOR_GEN)) > "$$tmp" && \
	diff -u test/monitor.v "$$tmp"

pll.v: timing
	icepll -m -f $@ -i 12 -o $(shell cat $^)

# rtl/imemory.v unconditionally $readmemh's this at elaboration time; it's
# gitignored and nothing generates it yet (real ROM contents are M1 work, once
# there's a test-binary-to-hex pipeline). An empty file is enough for
# synth_ice40 to elaborate — $readmemh on an empty file just leaves the ROM
# unmodified. Order-only prerequisite so it's not fed to read_verilog.
#
# This deliberately turns a hard yosys error into a successful build, so it has
# to say out loud that the resulting bitstream has an empty ROM and traps on its
# first instruction. Never silently.
rtl/rom.mem:
	touch $@
	@echo '*** WARNING: created an EMPTY $@ placeholder. Anything synthesised'
	@echo '*** from it has an uninitialised ROM and will trap on instruction 0.'
	@echo '*** Real ROM contents are M1 work (JEF-6xx: test-binary-to-hex).'

riscv.json: rtl/structs.v rtl/accessor.v rtl/decoder.v rtl/executor.v rtl/fetcher.v rtl/regfile.v rtl/writeback.v rtl/littlecpu.v rtl/littlesoc.v rtl/imemory.v rtl/memory.v | rtl/rom.mem
	yosys -p 'read_verilog -sv $^; synth_ice40 -dsp -top littlesoc -json $@'

riscv.asc: riscv.json riscv.pcf
	nextpnr-ice40 --up5k --json riscv.json --pcf riscv.pcf --asc riscv.asc --pcf-allow-unconstrained --opt-timing

timing: riscv.asc
	icetime -d up5k $^ | egrep -oi '\(\d+' | egrep -o '\d+' > $@

clean:
	rm -f riscv.json
	rm -f riscv.asc
	rm -f timing
	rm -f pll.v
	rm -f waves.vcd
	rm -rf sim sim.dSYM
	rm -f testbench.vvp testbench.vcd
	rm -f test/rtl.cc
	rm -f rvfi_macros.vh
	@# NOT rtl/rom.mem: gitignored, untracked, and nothing regenerates real
	@# contents for it, so `clean` deleting it is unrecoverable data loss.

# The riscv-formal clone rule and its pin guard live in formal/pin.mk, included
# above, so the root and formal/ Makefiles cannot drift apart on it.
