include formal/pin.mk

# A recipe that dies partway through must not leave a truncated target behind
# looking newer than its prerequisites — several targets here are shell
# redirections, which create the output file before the generator has written
# a byte of it.
.DELETE_ON_ERROR:

# Macro names that turn RVFI on (ADR-0006), shared by both sim legs below so
# they can't drift apart on which -D flags mean "RVFI is live" -- the whole
# point of JEF-628 is that both legs check the same thing. One list of names;
# each consumer applies its own flag syntax (iverilog: -DNAME, yosys
# `read_verilog`: -D NAME) via $(addprefix ...) since no single literal string
# satisfies both.
RISCV_FORMAL_MACROS := RISCV_FORMAL RISCV_FORMAL_COMPRESSED RISCV_FORMAL_ALIGNED_MEM RISCV_FORMAL_NRET=1 RISCV_FORMAL_XLEN=32 RISCV_FORMAL_ILEN=32

rvfi_macros.vh: $(RISCV_FORMAL_DIR)/checks/rvfi_macros.py
	python3 $^ > $@

testbench.vvp: rtl/structs.v rtl/accessor.v rtl/decoder.v rtl/executor.v rtl/fetcher.v rtl/regfile.v rtl/writeback.v rtl/littlecpu.v rvfi_macros.vh test/testbench.v test/monitor.v
	iverilog -I./rtl/ -DICARUS $(addprefix -D,$(RISCV_FORMAL_MACROS)) -g2012 -o $@ $^

# `./sim` now requires --rom/--ram/--cycles (ADR-0007/ADR-0008's runner, not
# the old no-args VCD demo) — `make waves` is unmaintained here; use
# `./sim --rom ... --ram ... --cycles N --vcd waves.vcd` directly, or the
# iverilog leg (test/testbench.v) for waveform debugging.
waves.vcd: sim
	./sim

# -O2 -DNDEBUG: the sim binary is the primary runner (ADR-0007) and needs to
# run 46 tests well under a minute; -g -O0 (the old flags) is 5-10x slower
# for no benefit here. -isystem (not -I) for the vendored cxxrtl runtime
# headers so -Wall -Wextra -Werror only fails on warnings in code this repo
# owns, not on the third-party runtime's.
sim: test/cxxrtl.cc test/rtl.cc
	clang++ -O2 -DNDEBUG -std=c++17 -Wall -Wextra -Werror \
	  -isystem $$(yosys-config --datdir)/include/backends/cxxrtl/runtime $< -o $@

# test/monitor.sim.v is a build-time-only, gitignored derivative of the
# tracked test/monitor.v (JEF-628): yosys's AST_AUTOWIRE elaboration bug
# trips on `$time` used as a bare $display argument (four call sites --
# iverilog handles it fine, yosys does not), so the cxxrtl leg below reads
# this stripped copy instead. test/monitor.v itself stays pristine and
# tracked (CLAUDE.md invariant 7); regenerate this file, never hand-edit it,
# and never commit it.
test/monitor.sim.v: test/monitor.v
	sed -E 's/ at time %0t --------", ([A-Za-z0-9_]+), \$$time\)/ --------", \1)/' $< > $@

# $(RISCV_FORMAL_MACROS) turns on the rvfi_* ports and their driving logic
# throughout rtl/ and test/testbench.v's `monitor` instance (ADR-0006);
# only RISCV_FORMAL itself is actually read by rtl/ or test/testbench.v
# today, the rest ride along for consistency with testbench.vvp above.
# test/monitor.sim.v (not test/monitor.v) supplies the `monitor` module
# here; see its rule above for why.
test/rtl.cc: rtl/structs.v rtl/accessor.v rtl/decoder.v rtl/executor.v rtl/fetcher.v rtl/regfile.v rtl/writeback.v rtl/littlecpu.v rvfi_macros.vh test/testbench.v test/monitor.sim.v
	yosys -p 'read_verilog -sv $(addprefix -D ,$(RISCV_FORMAL_MACROS)) $^; hierarchy -top testbench; write_cxxrtl $@'

# test/monitor.v is generated by riscv-formal's monitor/generate.py at
# RISCV_FORMAL_SHA (formal/pin.mk — bump the pin there, not here). generate.py
# opens ../insns/isa_<isa>.txt relative to its own CWD, so it must be run from
# riscv-formal/monitor/, not the repo root (see ADR-0007). The tracked file is
# regenerated in place; use `make monitor-check` to check freshness without
# touching it.
MONITOR_GEN = cd $(RISCV_FORMAL_DIR)/monitor && python3 generate.py -i rv32imc -c 1 -a -p monitor

# Depends on the generator and the pin, NOT on the clone directory: a directory's
# mtime bumps on any write anywhere inside it, which would make routine builds
# overwrite this tracked file (CLAUDE.md invariant 7) at unpredictable moments and
# defeat the point of monitor-check. The clone is order-only.
test/monitor.v: $(RISCV_FORMAL_DIR)/monitor/generate.py formal/pin.mk | $(RISCV_FORMAL_DIR)
	$(MONITOR_GEN) > $(CURDIR)/$@

.PHONY: monitor-check
monitor-check: $(RISCV_FORMAL_DIR)/monitor/generate.py | $(RISCV_FORMAL_DIR)
	@tmp=$$(mktemp "$${TMPDIR:-/tmp}/monitor-check.XXXXXX"); \
	trap 'rm -f "$$tmp"' EXIT; \
	($(MONITOR_GEN)) > "$$tmp" && \
	diff -u test/monitor.v "$$tmp"

# Installs the RISC-V cross compiler the test suite is assembled with
# (ADR-0007/ADR-0008). Both packages are freestanding-only (no multilib/
# newlib needed, since the tests are `-nostdlib`), and both are verified
# real, bottled/packaged builds — not a hallucinated package name.
.PHONY: setup
setup:
ifeq ($(shell uname -s),Darwin)
	brew install riscv64-elf-gcc
else
	@echo "On Linux, install the RISC-V cross compiler with:"
	@echo "  sudo apt-get install gcc-riscv64-unknown-elf"
endif

# Three small benches that landed in JEF-605 with no runner (rtl/executor.v,
# rtl/memory.v, rtl/decoder.v respectively). Compiled and run straight
# through iverilog/vvp; each bench $fatal(1)s on a mismatch and $finish
# (exit 0) on success, so vvp's own exit code is the pass/fail signal — no
# output-parsing needed. A separate target from `test` (that one is the
# ADR-0007 cxxrtl regression gate over test/asm/*.S; these are RTL-level unit
# benches with their own, unrelated pass/fail mechanism) but `test` depends
# on it so one `make test` still catches everything.
.PHONY: test-units
test-units:
	@tmp=$$(mktemp -d "$${TMPDIR:-/tmp}/test-units.XXXXXX"); \
	trap 'rm -rf "$$tmp"' EXIT; \
	set -e; \
	echo "== exec_tb =="; \
	iverilog -I./rtl/ -g2012 -o $$tmp/exec_tb.vvp rtl/structs.v rtl/executor.v test/exec_tb.v; \
	vvp $$tmp/exec_tb.vvp; \
	echo "== mem_tb =="; \
	iverilog -I./rtl/ -g2012 -o $$tmp/mem_tb.vvp rtl/memory.v test/mem_tb.v; \
	vvp $$tmp/mem_tb.vvp; \
	echo "== decoder_tb =="; \
	iverilog -I./rtl/ -g2012 -o $$tmp/decoder_tb.vvp rtl/structs.v rtl/decoder.v test/decoder_tb.v; \
	vvp $$tmp/decoder_tb.vvp

# Assembles every test/asm/*.S (rv32im_zicsr, -nostdlib, ADR-0008's memory
# map), runs each under `sim`, and checks the pass/fail table against
# test/EXPECTED_FAIL — the sprint-1 baseline. Exits 0 only when the actual
# failure list matches that file exactly, so this is a working regression
# gate today, against the current (still-broken, see CLAUDE.md) core.
.PHONY: test
test: sim test-units
	@./test/run_tests.sh ./sim test/asm test/EXPECTED_FAIL

pll.v: timing
	icepll -m -f $@ -i 12 -o $(shell cat $^)

# rtl/imemory.v unconditionally $readmemh's this at elaboration time; it's
# gitignored and nothing generates it yet (real ROM contents are M1 work, once
# there's a test-binary-to-hex pipeline). An empty file is enough for
# synth_ice40 to elaborate — $readmemh on an empty file just leaves the ROM
# unmodified. Order-only prerequisite so it's not fed to read_verilog.
#
# This deliberately turns a hard yosys error into a successful build, so it has
# to say out loud that the resulting bitstream has an empty ROM and traps on its
# first instruction. Never silently.
rtl/rom.mem:
	touch $@
	@echo '*** WARNING: created an EMPTY $@ placeholder. Anything synthesised'
	@echo '*** from it has an uninitialised ROM and will trap on instruction 0.'
	@echo '*** Real ROM contents are M1 work (JEF-6xx: test-binary-to-hex).'

riscv.json: rtl/structs.v rtl/accessor.v rtl/decoder.v rtl/executor.v rtl/fetcher.v rtl/regfile.v rtl/writeback.v rtl/littlecpu.v rtl/littlesoc.v rtl/imemory.v rtl/memory.v | rtl/rom.mem
	yosys -p 'read_verilog -sv $^; synth_ice40 -dsp -top littlesoc -json $@'

riscv.asc: riscv.json riscv.pcf
	nextpnr-ice40 --up5k --json riscv.json --pcf riscv.pcf --asc riscv.asc --pcf-allow-unconstrained --opt-timing

timing: riscv.asc
	icetime -d up5k $^ | egrep -oi '\(\d+' | egrep -o '\d+' > $@

clean:
	rm -f riscv.json
	rm -f riscv.asc
	rm -f timing
	rm -f pll.v
	rm -f waves.vcd
	rm -rf sim sim.dSYM
	rm -f testbench.vvp testbench.vcd
	rm -f test/rtl.cc
	rm -f test/monitor.sim.v
	rm -f rvfi_macros.vh
	@# NOT rtl/rom.mem: gitignored, untracked, and nothing regenerates real
	@# contents for it, so `clean` deleting it is unrecoverable data loss.

# The riscv-formal clone rule and its pin guard live in formal/pin.mk, included
# above, so the root and formal/ Makefiles cannot drift apart on it.
