include formal/pin.mk

rvfi_macros.vh: formal/riscv-formal/checks/rvfi_macros.py
	python $^ > $@

testbench.vvp: rtl/structs.v rtl/accessor.v rtl/decoder.v rtl/executor.v rtl/fetcher.v rtl/regfile.v rtl/writeback.v rtl/littlecpu.v rvfi_macros.vh test/testbench.v test/monitor.v
	iverilog -I./rtl/ -DICARUS -DRISCV_FORMAL -DRISCV_FORMAL_COMPRESSED -DRISCV_FORMAL_ALIGNED_MEM -DRISCV_FORMAL_NRET=1 -DRISCV_FORMAL_XLEN=32 -DRISCV_FORMAL_ILEN=32 -g2012 -o $@ $^

waves.vcd: sim
	./sim

sim: test/cxxrtl.cc test/rtl.cc
	clang++ -g -std=c++14 -I $$(yosys-config --datdir)/include/backends/cxxrtl/runtime $< -o $@

test/rtl.cc: rtl/structs.v rtl/accessor.v rtl/decoder.v rtl/executor.v rtl/fetcher.v rtl/regfile.v rtl/writeback.v rtl/littlecpu.v rvfi_macros.vh test/testbench.v
	yosys -p 'read_verilog -sv $^; hierarchy -top testbench; write_cxxrtl $@'

# test/monitor.v is generated by riscv-formal's monitor/generate.py, pinned
# at SHA c992aa61fdfe0846c5ed90324c596202a1c69b76 (RISCV_FORMAL_SHA in
# formal/pin.mk — bump the pin there, not here). generate.py opens
# ../insns/isa_<isa>.txt relative to its own CWD, so it must be run from
# riscv-formal/monitor/, not the repo root (see ADR-0007). The tracked file
# is regenerated in place; use `make monitor-check` to check freshness
# without touching it.
MONITOR_GEN = cd formal/riscv-formal/monitor && python3 generate.py -i rv32imc -c 1 -a -p monitor

test/monitor.v: formal/riscv-formal
	$(MONITOR_GEN) > $(CURDIR)/$@

.PHONY: monitor-check
monitor-check: formal/riscv-formal
	@tmp=$$(mktemp "$${TMPDIR:-/tmp}/monitor-check.XXXXXX"); \
	trap 'rm -f "$$tmp"' EXIT; \
	($(MONITOR_GEN)) > "$$tmp" && \
	diff -u test/monitor.v "$$tmp"

pll.v: timing
	icepll -m -f $@ -i 12 -o $(shell cat $^)

# rtl/imemory.v unconditionally $readmemh's this at elaboration time; it's
# gitignored and nothing generates it yet (real ROM contents are M1 work,
# once there's a test-binary-to-hex pipeline). An empty file is enough for
# synth_ice40 to elaborate — $readmemh on an empty file just leaves the ROM
# unmodified. Order-only prerequisite so it's not fed to read_verilog.
rtl/rom.mem:
	touch $@

riscv.json: rtl/structs.v rtl/accessor.v rtl/decoder.v rtl/executor.v rtl/fetcher.v rtl/regfile.v rtl/writeback.v rtl/littlecpu.v rtl/littlesoc.v rtl/imemory.v rtl/memory.v | rtl/rom.mem
	yosys -p 'read_verilog -sv $^; synth_ice40 -dsp -top littlesoc -json $@'

riscv.asc: riscv.json riscv.pcf
	nextpnr-ice40 --up5k --json riscv.json --pcf riscv.pcf --asc riscv.asc --pcf-allow-unconstrained --opt-timing

timing: riscv.asc
	icetime -d up5k $^ | egrep -oi '\(\d+' | egrep -o '\d+' > $@

clean:
	rm -f riscv.json
	rm -f riscv.asc
	rm -f timing
	rm -f pll.v
	rm -f waves.vcd
	rm -rf sim sim.dSYM
	rm -f testbench.vvp testbench.vcd
	rm -f test/rtl.cc
	rm -f rvfi_macros.vh
	rm -f rtl/rom.mem

formal/riscv-formal:
	git clone https://github.com/YosysHQ/riscv-formal.git $@
	git -C $@ checkout $(RISCV_FORMAL_SHA)
