#!/usr/bin/env python3
"""Write the spike instruction memory: rtl/imemory.v with two parameters added.

GENERATED, NOT COPIED. A second copy of rtl/imemory.v would diverge from it the
first time that file changed, silently, and the spike's `base` control -- which
exists to show the spike memory places the same as the shipping one -- would stop
controlling for anything. So the two edits are made against anchors that must be
present; a moved anchor stops this script rather than producing a memory that is
missing one of them.

WHAT THE PARAMETERS DO. Today's fetch loop is a combinational loop that leaves a
block RAM's data output, crosses decode, reaches `next_pc`, and closes inside the
same block RAM's address decode -- the memory is at both ends of it. There are
exactly two places a register can go to break that loop, and each takes the
memory out of one end:

  REG_ADDR  a register between `imem_addr_next` and the ROM's address decode, so
            the loop closes at a flip-flop and the ROM's addressing is off the
            tail;
  REG_DATA  a register between the ROM's read data and `imem_data`, so the loop
            starts at a flip-flop and the RAM's clock-to-output is off the head.

Both together leave a loop that touches no memory at all, which is the shape
VexRiscv has. So the three settings are the depth curve as well as the
memory-out-of-the-loop candidates: they are one experiment, because a register is
the only thing that takes a synchronous memory out of a combinational loop, and a
register in the fetch loop is a fetch stage.

The result is functionally WRONG on purpose -- it delays the fetch window without
giving decode anything to wait on, so a core built from it runs a program nobody
wrote. It is for placing and timing, not for simulating, and every number it
produces is a CEILING: a working core would have to add back a valid bit, a
redirect and whatever refills the window, all of it landing in the loop these
have just emptied.

Usage: variants.py <output.v>
"""

import pathlib
import sys

SOURCE = pathlib.Path(__file__).resolve().parents[2] / "rtl" / "imemory.v"

PARAMS_ANCHOR = '  parameter INIT_ODD  = ""\n) ('
PARAMS = '''  parameter INIT_ODD  = "",
  parameter integer REG_ADDR = 0,
  parameter integer REG_DATA = 0
) ('''

ADDR_ANCHOR = "  assign next_word  = imem_addr_next[31:2];"
ADDR = """  // With REG_ADDR clear this register has no reader and yosys deletes it, so the
  // zero setting really is the shipping netlist.
  logic [31:0] addr_q, fetch_addr;
  always_ff @(posedge clk) addr_q <= imem_addr_next;
  assign fetch_addr = (REG_ADDR != 0) ? addr_q : imem_addr_next;
  assign next_word  = fetch_addr[31:2];"""

DATA_ANCHOR = """  assign imem_data  = in_range  ? window_lo : 32'b0;
  assign imem_data2 = in_range2 ? window_hi : 32'b0;"""
DATA = """  // The window mux and the range gate stay on the memory's side of the new
  // register: the point is to leave the loop starting at a flip-flop rather than
  // at `SB_RAM40_4K`'s clock-to-output.
  logic [31:0] window_gated, window2_gated, data_q, data2_q;
  assign window_gated  = in_range  ? window_lo : 32'b0;
  assign window2_gated = in_range2 ? window_hi : 32'b0;
  always_ff @(posedge clk) begin
    data_q  <= window_gated;
    data2_q <= window2_gated;
  end
  assign imem_data  = (REG_DATA != 0) ? data_q  : window_gated;
  assign imem_data2 = (REG_DATA != 0) ? data2_q : window2_gated;"""

EDITS = [("parameter list", PARAMS_ANCHOR, PARAMS),
         ("fetch address", ADDR_ANCHOR, ADDR),
         ("fetch data", DATA_ANCHOR, DATA)]

BANNER = """// GENERATED by soc/depth/variants.py from rtl/imemory.v -- do not edit, and do
// not commit. A spike: functionally wrong on purpose, for placing and timing
// only. Read that script's header for what the two parameters do.
"""


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: variants.py <output.v>")
    text = SOURCE.read_text()
    for name, anchor, replacement in EDITS:
        if text.count(anchor) != 1:
            sys.exit(
                f"error: {SOURCE} does not contain the {name} anchor exactly once:\n"
                f"{anchor}\n"
                "This spike edits that file rather than copying it, so an anchor that "
                "moved has to be re-found, not worked around."
            )
        text = text.replace(anchor, replacement, 1)
    pathlib.Path(sys.argv[1]).write_text(BANNER + text)


if __name__ == "__main__":
    main()
